@startuml UC5 – Consulter les détails d'un restaurant (Diagramme de Séquence Système)

skinparam sequenceArrowThickness 1.5
skinparam roundcorner 5
skinparam sequenceParticipantBorderColor #6FA8DC
skinparam sequenceParticipantBackgroundColor #CFE2F3
skinparam sequenceActorBorderColor #6FA8DC
skinparam sequenceActorBackgroundColor #CFE2F3
skinparam sequenceLifeLineBorderColor #6FA8DC
skinparam SequenceGroupBorderColor #6FA8DC
skinparam SequenceGroupBackgroundColor #E8F0FB
skinparam SequenceGroupBodyBackgroundColor #FFFFFF

title interaction Consulter les détails d'un restaurant

actor "Utilisateur: Actor1" as U
participant "Système" as S

ref over U, S : (S'authentifier)

U -> S : 1 : Cliquer sur un restaurant
S --> U : 2 : Afficher la fiche du restaurant\n(informations, menu, avis, promotions)

@enduml
